### ISSUE TITLE
I open the gui with the "sudo ./escape.py -fV -s examples/escape-mn-req.nffg". but i get wrong

### ISSUE THREAD

**Issue by auyeungcarl** [hsnlab/escape#1]
Got exception during notifying remote Visualizer: HTTPConnectionPool(host='127.0.0.1', port=9999): Max retries exceeded with url: /notification?instance=ESCAPE&event=response (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f2dbf2bbc50>: Failed to establish a new connection: [Errno 111] Connection refused',))!

I don't know how to solve the problen.

**Comment by czeni** [comment]
1. The message you got is a simple warning that indicates the notification of the remote server was unsuccessful due to failed connection attempts. Just abandon the -V initial parameter.
2. Our rudimentary GUI is no longer shipped with ESCAPE because the utilized base code is incompatible with ESCAPE's Apache 2.0 license. The -g initial parameter has no effect. 
See the relevant help enty:
     >  -g, --gui             (OBSOLETE) initiate the graph-viewer GUI app which automatically connects to the ROS REST-API
